/**
 * WASM TypeScript Type Generator
 *
 * Reads wasm-bindgen's generated `.d.ts` and merges it with
 * additional module manifest metadata to produce a single
 * comprehensive type declaration file for the project.
 *
 * Usage: npx tsx scripts/gen-wasm-types.ts
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

function generate() {
  const pkgDts = resolve(ROOT, 'wasm/pkg/wasm_unified_core.d.ts');
  const outDts = resolve(ROOT, 'src/wasm-types.d.ts');

  if (!existsSync(pkgDts)) {
    console.warn(
      '⚠️  wasm/pkg/wasm_unified_core.d.ts not found. Run wasm-pack build first.',
    );
    return;
  }

  const generated = readFileSync(pkgDts, 'utf-8');

  const enhanced = `// ============================================================================
// Auto-generated WASM type declarations
// DO NOT EDIT — generated by scripts/gen-wasm-types.ts
// Source: wasm/pkg/wasm_unified_core.d.ts
// ============================================================================

import type {
  InitInput as WasmInitInput,
  InitOutput as WasmInitOutput,
  SyncInitInput as WasmSyncInitInput,
} from '../../wasm/pkg/wasm_unified_core';

export type {
  WasmInitInput,
  WasmInitOutput,
  WasmSyncInitInput,
};

// ── Module Manifest ──

/**
 * Metadata about a registered Rust WASM module.
 * Retrieved at runtime via \`get_module_manifests_json()\`.
 */
export interface WasmModuleManifest {
  name: string;
  version: string;
  description: string;
  state_keys: string[];
}

// ── Action Dispatch Result ──

/**
 * Result of \`engine.dispatch_action()\`.
 * Parsed from the JSON string returned by Rust.
 */
export interface WasmDispatchResult {
  ok: boolean;
  events?: WasmModuleEvent[];
  error?: WasmModuleError;
}

/**
 * A structured error from a WASM module.
 */
export interface WasmModuleError {
  code: string;
  message: string;
  details?: unknown;
}

/**
 * An event emitted by a WASM module during action handling.
 * Events are accumulated and drained by \`engine.drain_events()\`.
 */
export interface WasmModuleEvent {
  module: string;
  name: string;
  data: unknown;
}

// ── Component State ──

/**
 * Bidirectional state between TypeScript and Rust.
 * Stored as a flat key-value map in the engine.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface WasmComponentState extends Record<string, unknown> {
  count?: number;
  title?: string;
  items?: string[];
  greet_msg?: string;
  fib_val?: number;
  processed_text?: string;
  search_query?: string;
  selected_category?: string;
  filtered_items?: WasmMenuItem[];
  password_result?: string;
  hash_result?: string;
}

export interface WasmMenuItem {
  title: string;
  description: string;
  tag: string;
  tag_class: string;
  icon_svg: string;
  action_id: string;
}

// ── Re-export CoreEngine (passthrough) ──

export { CoreEngine, init_core, run_async_task, get_module_manifests_json } from '../../wasm/pkg/wasm_unified_core';

// ── Helper: infer state type from a component ──

export type StateOf<T> = T extends { state: { value: infer S } } ? S : never;
`;

  writeFileSync(outDts, enhanced, 'utf-8');
  console.log(`✅ Generated ${outDts}`);
}

generate();
